[project]
authors = ["Jack Myers <jack.myers@intel.com>"]
channels = ["conda-forge"]
description = "Add a short description here"
name = "llvm-sycl"
platforms = ["linux-64"]
version = "20.0.0"

[feature.runtime.target.linux-64.dependencies]
gcc = ">=13.3.0,<13.4"
gxx = ">=13.3.0,<13.4"
cuda = ">=12.6.3,<12.7"
pkg-config = ">=0.29.2,<0.30"
pkgconfig = ">=1.5.5,<1.6"
sysroot_linux-64 = ">=2.34"
intel-opencl-rt = ">=2024.2.1,<2025.1"
intel-fortran-rt = ">=2024.2.1,<2025.1"
clinfo = ">=3.0.21.2.21,<3.1"
tbb-devel = ">=2022.0.0,<2022.1"
libxml2 = ">=2.13.5,<2.14"
zlib = ">=1.3.1,<1.4"
libhwloc = ">=2.11.2,<2.12"
zstd-static = ">=1.5.6,<1.6"
backtrace = ">=20220708,<20220708.1"

[target.linux-64.build-dependencies]
cmake = "3.24.*"
gcc = ">=13.3.0,<14.3"
gxx = ">=13.3.0,<14.3"
cxx-compiler = ">=1.0.0,<1.9"
c-compiler = ">=1.0.0,<1.9"
python = ">=3.13.0,<3.14"
pkgconfig = ">=1.5.5,<1.6"
pkg-config = ">=0.29.2,<0.30"
git = ">=2.47.1,<2.48"
ninja = ">=1.12.1,<1.13"
wget = ">=1.21.4,<1.22"
ccache = ">=4.10.1,<4.11"
patchelf = ">=0.17.2,<0.18"
lld = ">=19.1.4,<20"
file = ">=5.39,<6"

[target.linux-64.host-dependencies]
gcc = ">=13.3.0,<13.4"
gxx = ">=13.3.0,<13.4"
cuda = ">=12.6.3,<12.7"
pkg-config = ">=0.29.2,<0.30"
pkgconfig = ">=1.5.5,<1.6"
sysroot_linux-64 = ">=2.34"
intel-opencl-rt = ">=2024.2.1,<2025.1"
intel-fortran-rt = ">=2024.2.1,<2025.1"
clinfo = ">=3.0.21.2.21,<3.1"
tbb-devel = ">=2022.0.0,<2022.1"
libxml2 = ">=2.13.5,<2.14"
zlib = ">=1.3.1,<1.4"
libhwloc = ">=2.11.2,<2.12"
zstd-static = ">=1.5.6,<1.6"
backtrace = ">=20220708,<20220708.1"
x86_64-microarch-level = "<=3"

[target.linux-64.activation]
scripts = ["../activation/linux.sh", "env.sh"]
env = { INSTALL_PREFIX = "$HOME/dpcpp", INSTALL_RPATHS = "\\$ORIGIN;\\$ORIGIN/../lib;\\$ORIGIN/../lib64" }

[target.linux-64.tasks]
configure = { cmd = "bash scripts/configure.sh" }
install = { cmd = "bash scripts/install.sh" }
test = { cmd = "bash scripts/test.sh" }
patch-rpaths = "bash scripts/patch_installed_rpaths.sh"

[environments]
runtime = ["runtime"]
