set(CMAKE_C_COMPILER "$ENV{CC}")
set(CMAKE_CXX_COMPILER "$ENV{CXX}")

if(NOT "$ENV{NO_INSTALL_RPATH}" STREQUAL "1")
  if("$ENV{INSTALL_RPATHS}" STREQUAL "")
    set(CMAKE_INSTALL_RPATH "\$ORIGIN;\$ORIGIN/../lib;\$ORIGIN/../lib64")
  else()
    set(CMAKE_INSTALL_RPATH "$ENV{INSTALL_RPATHS}")
  endif()
  set(CMAKE_SKIP_RPATH
      FALSE
      CACHE BOOL "" FORCE)
  set(CMAKE_SKIP_INSTALL_RPATH
      FALSE
      CACHE BOOL "" FORCE)
  set(CMAKE_SKIP_BUILD_RPATH
      FALSE
      CACHE BOOL "" FORCE)
endif()

set(CUDAToolkit_ROOT
    "$ENV{CONDA_CUDA_ROOT}"
    CACHE PATH "")
set(CUDA_TOOLKIT_ROOT_DIR
    "$ENV{CONDA_CUDA_ROOT}"
    CACHE PATH "")
