#!/bin/bash

set -e

mkdir -p "$SUBPROJECT_ROOT/onemkl/build"
cd "$SUBPROJECT_ROOT/onemkl/build"

rm -f CMakeCache.txt

cmake .. -G Ninja \
  -DCMAKE_C_COMPILER_LAUNCHER=ccache \
  -DCMAKE_CXX_COMPILER_LAUNCHER=ccache \
  -DCMAKE_TOOLCHAIN_FILE="$PROJECT_TOOLCHAIN_FILE" \
  -DENABLE_MKLCPU_BACKEND=True \
  -DENABLE_MKLGPU_BACKEND=True \
  -DENABLE_CUBLAS_BACKEND=True \
  -DENABLE_CUSOLVER_BACKEND=True \
  -DENABLE_CUFFT_BACKEND=True \
  -DENABLE_CUSPARSE_BACKEND=True \
  -DENABLE_CURAND_BACKEND=True \
  -DBUILD_FUNCTIONAL_TESTS=False \
  -DBUILD_EXAMPLES=False \
  -DCMAKE_CXX_FLAGS="$CXXFLAGS" \
  -DCMAKE_INSTALL_PREFIX="$INSTALL_PREFIX" \
  $CMAKE_ARGS
