# oneMath Recipe for rattler-build
# SYCL math library wrapping NVIDIA CUDA math libraries (cuBLAS, cuSOLVER, etc.)
#
# Build with:
#   cd packages/onemath && pixi build
#
# Or directly with rattler-build:
#   rattler-build build -r recipe/recipe.yaml
#
# Build Strategy:
#   This recipe builds directly in the repo directory (not a copy) to enable
#   incremental builds. Each output runs the build script, but since we build
#   in-place, subsequent outputs just do a quick incremental "rebuild" (no-op
#   if nothing changed) and then install to PREFIX.

schema_version: 1

context:
  name: naga-onemath
  version: "2026.2.16"

recipe:
  name: ${{ name }}
  version: ${{ version }}

source:
  # Use a minimal dummy directory to avoid copying the full repo
  # The build script uses RECIPE_DIR/../repo as the actual source
  path: ../src

build:
  skip:
    - win
    - osx

outputs:
  # ==========================================================================
  # Runtime libraries only (smallest footprint)
  # ==========================================================================
  - package:
      name: ${{ name }}-libs
      version: ${{ version }}
    build:
      script: scripts/build.sh
      files:
        # Runtime shared libraries
        - lib/*.so*
    requirements:
      build:
        - naga-adaptivecpp-toolkit >=2026.2.16,<2027
        - ${{ stdlib('c') }}
        - cmake >=3.24
        - ninja >=1.12
        - ccache
        - pkg-config
        - git
        # CUDA dependencies - cuda-toolkit metapackage handles version coordination
        # cuda-version pins the CUDA version, cuda-toolkit pulls all dev libraries
        - cuda-version >=12.6,<13
        - cuda-toolkit
      run:
        - ${{ stdlib('c') }}
        - naga-adaptivecpp-toolkit-libs >=2026.2.16,<2027
        # Runtime CUDA libraries (pulled transitively via cuda-toolkit's cuda-libraries)
        - cuda-cudart
      run_exports:
        - ${{ pin_subpackage(name ~ '-libs', upper_bound='x.x') }}
    tests:
      - script:
          - test -f $PREFIX/lib/libonemath.so || test -f $PREFIX/lib/libonemath_blas_cublas.so

  # ==========================================================================
  # Development libraries (headers, cmake files)
  # ==========================================================================
  - package:
      name: ${{ name }}-devel
      version: ${{ version }}
    build:
      script: scripts/build.sh
      files:
        # All headers
        - include/**
        # CMake modules
        - lib/cmake/**
        # pkg-config files
        - lib/pkgconfig/**
    requirements:
      build:
        - naga-adaptivecpp-toolkit >=2026.2.16,<2027
        - ${{ stdlib('c') }}
        - cmake >=3.24
        - ninja >=1.12
        - ccache
        - pkg-config
        - git
        # CUDA dependencies - cuda-toolkit metapackage handles version coordination
        # cuda-version pins the CUDA version, cuda-toolkit pulls all dev libraries
        - cuda-version >=12.6,<13
        - cuda-toolkit
      run:
        - ${{ name }}-libs ==${{ version }}
        - naga-adaptivecpp-toolkit-devel >=2026.2.16,<2027
    tests:
      - script:
          - test -d $PREFIX/include/oneapi/math || test -d $PREFIX/include/oneapi/mkl

  # ==========================================================================
  # Full package (meta-package that pulls in everything)
  # ==========================================================================
  - package:
      name: ${{ name }}
      version: ${{ version }}
    build:
      script: scripts/build.sh
      # No additional files - this is a meta-package
      files: []
    requirements:
      build:
        - naga-adaptivecpp-toolkit >=2026.2.16,<2027
        - ${{ stdlib('c') }}
        - cmake >=3.24
        - ninja >=1.12
        - ccache
        - pkg-config
        - git
        # CUDA dependencies - cuda-toolkit metapackage handles version coordination
        # cuda-version pins the CUDA version, cuda-toolkit pulls all dev libraries
        - cuda-version >=12.6,<13
        - cuda-toolkit
      run:
        - ${{ name }}-libs ==${{ version }}
        - ${{ name }}-devel ==${{ version }}
        - naga-adaptivecpp-toolkit >=2026.2.16,<2027
      run_exports:
        - ${{ pin_subpackage(name ~ '-libs', upper_bound='x.x') }}
    tests:
      - script:
          - test -d $PREFIX/include/oneapi

about:
  summary: oneMath - SYCL math library with NVIDIA CUDA backend support
  description: |
    oneMath (formerly oneMKL Interfaces) provides a unified SYCL interface
    to vendor-optimized math libraries. This package builds with NVIDIA CUDA
    backends:

    Packages:
    - naga-onemath-libs: Runtime libraries only
    - naga-onemath-devel: Development files (headers, cmake)
    - naga-onemath: Full package (meta-package)

    Supported domains:
    - BLAS (cuBLAS backend)
    - LAPACK (cuSOLVER backend)
    - RNG (cuRAND backend)
    - DFT/FFT (cuFFT backend)
    - Sparse BLAS (cuSPARSE backend)

    Usage:
      #include <oneapi/math.hpp>
      // or legacy: #include <oneapi/mkl.hpp>
  license: Apache-2.0
  license_file: LICENSE
  homepage: https://github.com/uxlfoundation/oneMath
  repository: https://github.com/NAGAGroup/CodeAccelerate-SYCLBuildKit
  documentation: https://oneapi-spec.uxlfoundation.org/specifications/oneapi/latest/elements/onemath/source/

extra:
  recipe-maintainers:
    - jackm97
