schema_version: 1

context:
  name: naga-adaptivecpp-toolkit
  version: "2026.2.17"

recipe:
  name: ${{ name }}
  version: ${{ version }}

# NOTE: Channels must be specified at build-time via CLI flags:
#   rattler-build build -c conda-forge
# This is required to resolve compiler('c') and compiler('cxx') dependencies.

source:
  # Use a minimal dummy directory to avoid copying files
  # The build script uses RECIPE_DIR/../repo as the actual source
  path: ../src

build:
  skip:
    - win
    - osx

outputs:
  # Output 1: Runtime libraries
  - package:
      name: ${{ name }}-libs
      version: ${{ version }}

    build:
      script: scripts/build.sh
      files:
        - lib/**/*.so*
        - etc/AdaptiveCpp/*
    requirements:
      build:
        - ${{ compiler('c') }}
        - ${{ compiler('cxx') }}
        - ${{ stdlib('c') }}
        - cuda >=12,<13
        - cmake >=3.24
        - ninja >=1.12
        - python >=3.10
        - git
        - ccache
        - lld >=18
        - boost-cpp >=1.84
        - llvmdev >=18,<19
      run:
        - ${{ stdlib('c') }}
        - libstdcxx ${{ cxx_compiler_version }}
        - boost-cpp >=1.84
        - libedit
      run_exports:
        - ${{ pin_subpackage(name ~ '-libs', upper_bound='x.x') }}

    tests:
      - script:
          - test -f $PREFIX/lib/libacpp_runtime.so

  # Output 2: Development headers
  - package:
      name: ${{ name }}-devel
      version: ${{ version }}

    build:
      script: scripts/build.sh
      files:
        - lib/cmake/*
        - include/*

    requirements:
      build:
        - ${{ compiler('c') }}
        - ${{ compiler('cxx') }}
        - ${{ stdlib('c') }}
        - cuda >=12,<13
        - cmake >=3.24
        - ninja >=1.12
        - python >=3.10
        - git
        - ccache
        - lld >=18
        - boost-cpp >=1.84
        - llvmdev >=18,<19
      run:
        - ${{ name }}-libs ==${{ version }}
        - boost-cpp >=1.84
        - libstdcxx-devel_linux-64 ${{ cxx_compiler_version }}

    tests:
      - script:
          - test -f $PREFIX/include/sycl/sycl.hpp
          - test -d $PREFIX/lib/cmake/AdaptiveCpp

  # Output 3: Full toolkit
  - package:
      name: ${{ name }}
      version: ${{ version }}

    build:
      script: scripts/build.sh
      files:
        exclude:
          - lib/cmake/*
          - include/*
          - lib/**/*.so*
          - etc/AdaptiveCpp/*
    requirements:
      build:
        - ${{ compiler('c') }}
        - ${{ compiler('cxx') }}
        - ${{ stdlib('c') }}
        - cuda >=12,<13
        - cmake >=3.24
        - ninja >=1.12
        - python >=3.10
        - git
        - ccache
        - lld >=18
        - boost-cpp >=1.84
        - llvmdev >=18,<19
      run:
        - ${{ name }}-libs ==${{ version }}
        - ${{ name }}-devel ==${{ version }}
        - python >=3.10
        - gcc ${{ c_compiler_version }}
        - gxx ${{ cxx_compiler_version }}

    tests:
      - script:
          - acpp --version
          - acpp-info --list-targets
          - clang++ --version
