context:
  name: sycl-dpcpp
  version: "2025.0.0"

recipe:
  name: ${{ name|lower }}
  version: ${{ version }}

cache:
  source:
    path: ../repo
  requirements:
    build:
      - ${{ compiler('c') }}
      - ${{ compiler('cxx') }}
      - ${{ stdlib('c') }}
      - ccache
      - git
      - python >=3.10,<3.13
      - cmake >=3.24
      - pkg-config
      - pkgconfig
      - ninja >=1.12
      - wget
      - lld >=19
      - patchelf
      - file
    host:
      - cuda-toolkit ==${{ cuda_compiler_version }}
      - cuda-nvcc ==${{ cuda_compiler_version }}
      - zstd-static >=1.5
      - libxml2 >=2.12
      - zlib >=1.3
      - libhwloc >=2.11
      - tbb-devel >=2021
      - ocl-icd >=2.3
      - libopencl-devel

  build:
    skip:
      - win
      - osx
      - match(cuda_compiler_version, "<12")
    script: scripts/build-package.sh

outputs:
  # Runtime libraries only
  - package:
      name: ${{ name }}-libs
    build:
      script: scripts/install-libs.sh
    requirements:
      run:
        - cuda-libraries ==${{ cuda_compiler_version }}
        - ocl-icd
        - libhwloc >=2.11
        - tbb >=2021
      run_exports:
        - ${{ name }}-libs ==${{ version }}
      run_constraints:
        # Prevent conflicts with conda-forge LLVM packages
        - libllvm ==999999999
        - libclang ==999999999
        - libclang-cpp ==999999999
        - clang-tools ==999999999
        - libllvmspirv ==999999999

  # Development libraries (headers, cmake files)
  - package:
      name: ${{ name }}-libs-devel
    build:
      script: scripts/install-libs-devel.sh
    requirements:
      run:
        - cuda-libraries-dev ==${{ cuda_compiler_version }}
        - ${{ pin_subpackage(name ~ '-libs', exact=True) }}

  # Full toolkit (compiler, tools, everything)
  - package:
      name: ${{ name }}-toolkit
    build:
      script: scripts/install-toolkit.sh
    requirements:
      run:
        - cuda-toolkit ==${{ cuda_compiler_version }}
        - ${{ pin_subpackage(name ~ '-libs-devel', exact=True) }}

about:
  summary: Intel DPC++ SYCL compiler with NVIDIA CUDA support
  description: |
    Intel DPC++ is an open-source SYCL compiler based on LLVM/Clang.
    This package provides full NVIDIA GPU support via the CUDA backend,
    enabling portable heterogeneous programming across CPUs and GPUs.
    
    Key features:
    - SYCL 2020 support
    - NVIDIA CUDA backend
    - OpenCL backend
    - Native CPU backend
    - Unified Shared Memory (USM)
    - Runtime compilation (sycl-jit)
  license: Apache-2.0
  license_file:
    - LICENSE.TXT
  homepage: https://github.com/intel/llvm
  repository: https://github.com/NAGAGroup/CodeAccelerate-SYCLBuildKit
  documentation: https://intel.github.io/llvm-docs/

extra:
  recipe-maintainers:
    - jackm97
