# SYCL Toolkit Recipe for rattler-build
# Intel DPC++ SYCL compiler with NVIDIA CUDA and Native CPU support
#
# Build with:
#   cd packages/llvm && pixi build
#
# Or directly with rattler-build:
#   rattler-build build -r recipe/recipe.yaml
#
# Build Strategy:
#   This recipe builds directly in the repo directory (not a copy) to enable
#   incremental builds. Each output runs the build script, but since we build
#   in-place, subsequent outputs just do a quick incremental "rebuild" (no-op
#   if nothing changed) and then install to PREFIX.

schema_version: 1

context:
  name: naga-sycl-toolkit
  version: "2025.12.1"

recipe:
  name: ${{ name }}
  version: ${{ version }}

source:
  # Use a minimal dummy directory to avoid copying 160k+ files
  # The build script uses RECIPE_DIR/../repo as the actual source
  path: ../src

build:
  skip:
    - win
    - osx

outputs:
  # ==========================================================================
  # Runtime libraries only (smallest footprint)
  # ==========================================================================
  - package:
      name: ${{ name }}-libs
      version: ${{ version }}
    build:
      script: scripts/build.sh
      files:
        # Runtime shared libraries (top-level only, not in subdirectories like lib/clang/)
        - lib/*.so*
        # SYCL runtime subdirectory
        - lib/sycl/**
        # OpenCL vendor files
        - etc/OpenCL/**
        # License
        - LICENSE.TXT
    requirements:
      build:
        - ${{ compiler('c') }}
        - ${{ compiler('cxx') }}
        - ${{ stdlib('c') }}
        - cmake >=3.24
        - ninja >=1.12
        - python >=3.10,<3.13
        - git
        - ccache
        - pkg-config
        - pkgconfig
        - lld >=19
        - patchelf
        - wget
        - file
      host:
        - cuda-toolkit >=12.6,<13
        - cuda-nvcc >=12.6,<13
        - zstd-static >=1.5
        - libxml2 >=2.12
        - zlib >=1.3
        - libhwloc >=2.11
        - tbb-devel >=2021
        - ocl-icd >=2.3
        - libopencl-devel >=3.0
      run:
        - cuda-cudart >=12.6,<13
        - ocl-icd
        - libhwloc >=2.11
        - tbb >=2021
      run_exports:
        - ${{ pin_subpackage(name ~ '-libs', upper_bound='x.x') }}
      run_constraints:
        # Prevent conflicts with conda-forge LLVM packages
        - libllvm ==999999999
        - libclang ==999999999
        - libclang-cpp ==999999999
        - clang-tools ==999999999
        - libllvmspirv ==999999999
    tests:
      - script:
          - test -f $PREFIX/lib/libsycl.so

  # ==========================================================================
  # Development libraries (headers, cmake files, static libs)
  # ==========================================================================
  - package:
      name: ${{ name }}-devel
      version: ${{ version }}
    build:
      script: scripts/build.sh
      files:
        # All headers
        - include/**
        # Static libraries
        - lib/*.a
        # CMake modules
        - lib/cmake/**
        # pkg-config files
        - lib/pkgconfig/**
        # Clang resource directory (includes, builtins, etc.)
        - lib/clang/**
    requirements:
      build:
        - ${{ compiler('c') }}
        - ${{ compiler('cxx') }}
        - ${{ stdlib('c') }}
        - cmake >=3.24
        - ninja >=1.12
        - python >=3.10,<3.13
        - git
        - ccache
        - pkg-config
        - pkgconfig
        - lld >=19
        - patchelf
        - wget
        - file
      host:
        - cuda-toolkit >=12.6,<13
        - cuda-nvcc >=12.6,<13
        - zstd-static >=1.5
        - libxml2 >=2.12
        - zlib >=1.3
        - libhwloc >=2.11
        - tbb-devel >=2021
        - ocl-icd >=2.3
        - libopencl-devel >=3.0
      run:
        - ${{ pin_subpackage(name ~ '-libs', exact=True) }}
        - cuda-cudart-dev >=12.6,<13
    tests:
      - script:
          - test -d $PREFIX/include/sycl
          - test -f $PREFIX/lib/cmake/LLVMSYCLLowerIR/LLVMSYCLLowerIRTargets.cmake || true

  # ==========================================================================
  # Full toolkit (compiler, tools, everything)
  # ==========================================================================
  - package:
      name: ${{ name }}
      version: ${{ version }}
    build:
      script: scripts/build.sh
      files:
        # All binaries
        - bin/**
        # LLVM utilities
        - libexec/**
        # Share directory (LLVM data files)
        - share/**
        # Activation scripts for environment setup
        - etc/conda/**
    requirements:
      build:
        - ${{ compiler('c') }}
        - ${{ compiler('cxx') }}
        - ${{ stdlib('c') }}
        - cmake >=3.24
        - ninja >=1.12
        - python >=3.10,<3.13
        - git
        - ccache
        - pkg-config
        - pkgconfig
        - lld >=19
        - patchelf
        - wget
        - file
      host:
        - cuda-toolkit >=12.6,<13
        - cuda-nvcc >=12.6,<13
        - zstd-static >=1.5
        - libxml2 >=2.12
        - zlib >=1.3
        - libhwloc >=2.11
        - tbb-devel >=2021
        - ocl-icd >=2.3
        - libopencl-devel >=3.0
      run:
        - ${{ pin_subpackage(name ~ '-devel', exact=True) }}
        - cuda-toolkit >=12.6,<13
      run_exports:
        - ${{ pin_subpackage(name ~ '-libs', upper_bound='x.x') }}
    tests:
      - script:
          - test -f $PREFIX/bin/clang++
          - test -f $PREFIX/bin/sycl-ls
          # Check triple-prefixed symlinks exist
          - test -L $PREFIX/bin/x86_64-conda-linux-gnu-clang
          - test -L $PREFIX/bin/x86_64-conda-linux-gnu-clang++
          # Check config file exists
          - test -f $PREFIX/bin/x86_64-conda-linux-gnu.cfg
          # Check activation scripts
          - test -f $PREFIX/etc/conda/activate.d/~~activate-sycl.sh
          - test -f $PREFIX/etc/conda/deactivate.d/~~deactivate-sycl.sh
          # Test compilers work
          - $PREFIX/bin/clang++ --version
          - $PREFIX/bin/x86_64-conda-linux-gnu-clang++ --version
          # sycl-ls may fail without GPU hardware
          - $PREFIX/bin/sycl-ls || echo "sycl-ls check skipped (no GPU)"

about:
  summary: Intel DPC++ SYCL compiler with NVIDIA CUDA support
  description: |
    Intel DPC++ is an open-source SYCL compiler based on LLVM/Clang.
    This package provides full NVIDIA GPU support via the CUDA backend,
    enabling portable heterogeneous programming across CPUs and GPUs.
    
    Packages:
    - naga-sycl-toolkit-libs: Runtime libraries only (for running SYCL apps)
    - naga-sycl-toolkit-devel: Development files (headers, cmake)
    - naga-sycl-toolkit: Full compiler and tools
    
    Key features:
    - SYCL 2020 support
    - NVIDIA CUDA backend
    - OpenCL backend
    - Native CPU backend
    - Unified Shared Memory (USM)
    - Runtime compilation (sycl-jit)
    
    To use:
      clang++ -fsycl -fsycl-targets=nvptx64-nvidia-cuda my_code.cpp
  license: Apache-2.0
  license_file: LICENSE.TXT
  homepage: https://github.com/intel/llvm
  repository: https://github.com/NAGAGroup/CodeAccelerate-SYCLBuildKit
  documentation: https://intel.github.io/llvm-docs/

extra:
  recipe-maintainers:
    - jackm97
